{-# LANGUAGE DerivingStrategies  #-}
{-# LANGUAGE LambdaCase          #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE RecordWildCards     #-}
{-# LANGUAGE ScopedTypeVariables #-}

-- | @krikit-regen-repo-inventory@: regenerate the categorized
-- repo inventory.
--
-- Inputs:
--
--   * @kritick-ecosystem\/docs\/ecosystem-roots.generated.md@
--     -- canonical exhaustive list of @kritick-*@ root repos.
--   * Filesystem walk of the workspace root (default
--     @~opsadmin\/Development\/@) -- catches every other prefix
--     (@krikit-*@, @purescript-*@, @scala-*@, @ng-kritick-*@, etc.)
--     plus surfaces uncategorized repos for follow-up.
--   * @kritick-ecosystem\/config\/ecosystem.json@ -- the @ignore@
--     and @skip_repo_prefixes@ filter rules.
--
-- Output:
-- @krikit-agent-fabric\/context\/repo-inventory.generated.md@.
--
-- Categorization is rule-based and *multi-category*: 'classify'
-- returns @'NonEmpty' 'Category'@ so a single repo can list under
-- more than one section. Examples:
--
--   * @elasticsearch-kritick-schema@ is database infrastructure
--     (Cloud-Formation + scripts) AND its mapping files are
--     autogenerated by @util-kritick-schema@. Lists in both.
--   * @kritick-admin@ is a customer-facing SPA AND the admin
--     backend service in one repo. Lists in both.
--
-- New categories require updating 'allCategories' + 'classify';
-- the compiler's exhaustiveness check on 'Category' enforces
-- consistency across heading, blurb, and dispatch.
module Krikit.Agent.Ops.RepoInventory.Run
    ( -- * Domain types
      Category (..)
    , Inventory (..)
    , EcosystemFilter (..)

      -- * Pure logic
    , allCategories
    , categoryHeading
    , categoryBlurb
    , classify
    , repoNote
    , buildInventory
    , applyFilter
    , extractEcosystemRoots

      -- * IO
    , readEcosystemFilter

      -- * Rendering
    , renderInventory

      -- * Effectful orchestrator
    , regenerate
    ) where

import           Control.Exception                    (IOException, try)
import           Data.Aeson                           (FromJSON (..), (.:?))
import qualified Data.Aeson                           as A
import qualified Data.ByteString.Lazy                 as LBS
import           Data.List                            (nub, sort)
import qualified Data.List.NonEmpty                   as NE
import           Data.List.NonEmpty                   (NonEmpty (..))
import qualified Data.Map.Strict                      as Map
import           Data.Map.Strict                      (Map)
import           Data.Maybe                           (fromMaybe)
import           Data.Set                             (Set)
import qualified Data.Set                             as Set
import           Data.Text                            (Text)
import qualified Data.Text                            as T
import qualified Data.Text.IO                         as TIO
import qualified Data.Time                            as Time

import           Effectful                            (Eff, IOE, liftIO, (:>))
import           Effectful.Reader.Static              (Reader, ask)

import           Krikit.Agent.Ops.Config
    ( Config (..)
    , EcosystemPaths (..)
    , FabricPaths (..)
    , PathsConfig (..)
    )
import           Krikit.Agent.Ops.Regen.Banner
    ( Banner (..)
    , BannerInputs (..)
    , renderBanner
    )
import           Krikit.Agent.Ops.Regen.FsWalk        (listRepoDirs)
import           Krikit.Agent.Ops.Regen.Write
    ( WriteOutcome
    , writeIfChanged
    )
import           Krikit.Agent.Ops.Regen.MarkdownExtract
    ( MarkdownTable (..)
    , extractFirstTable
    )

-- =============================================================================
-- Categories
-- =============================================================================

-- | Categories the inventory groups repos into. Order here defines
-- the section order in the rendered output.
--
-- @CatUnknown@ is the catch-all and always renders last; if any
-- repo lands there, that's a signal the taxonomy needs an update
-- and the verifier should flag it.
data Category
    -- Product (kritick-* customer-facing apps + supporting assets)
    = CatKritickProduct                -- ^ kritick-{admin, blog, customer, ...}
    | CatKritickProductSensitive       -- ^ supporting product assets, sensitive contents
    -- kritick-* services + coordination
    | CatKritickService                -- ^ kritick-{api, process, session, feature, ...}
    | CatKritickCoordination           -- ^ kritick-ecosystem
    -- krikit ops
    | CatKrikit                        -- ^ krikit-* (agent ops + fabric)
    -- Schema family
    | CatKritickSchema                 -- ^ util-kritick-schema + every *-kritick-*-schema output
    -- PureScript kritick-domain (split by sub-shape)
    | CatPureScriptKritickData         -- ^ purescript-kritick-*-data (domain ADTs)
    | CatPureScriptKritickReact        -- ^ purescript-kritick-react-* (kritick-themed React UI)
    | CatPureScriptKritickOther        -- ^ purescript-kritick-* (programs, dateutil, email-templates...)
    -- PureScript general
    | CatPureScriptFree                -- ^ purescript-*-free
    | CatPureScriptData                -- ^ purescript-*-data
    | CatPureScriptReact               -- ^ purescript-react-* (web)
    | CatPureScriptReactNative         -- ^ purescript-react-native-*
    | CatPureScriptCodecs              -- ^ encoding / serialization libraries
    | CatPureScriptStandards           -- ^ ISO standards (3166, 4217, 639, 8601)
    | CatPureScriptDateTime            -- ^ date / time helpers
    | CatPureScriptGeographic          -- ^ geographic data types
    | CatPureScriptIdentifiers         -- ^ id-shaped value types
    | CatPureScriptOther               -- ^ remaining purescript-* misc
    -- Scala
    | CatScalaKritick                  -- ^ scala-kritick-* (non-schema)
    | CatScalaFree                     -- ^ scala-*-free (non-kritick)
    | CatScalaData                     -- ^ scala-*-data (non-kritick)
    | CatScalaOther                    -- ^ scala-* misc
    -- Angular / React / Util / Template
    | CatNgKritick                     -- ^ ng-kritick-* + ng-* known-name set
    | CatReact                         -- ^ react-* / react-kritick-*
    | CatUtil                          -- ^ util-* (non-schema)
    | CatTemplate                      -- ^ template-* repo scaffolds
    -- Build / infra / asset
    | CatBuildTooling                  -- ^ build / deploy / lint / publish
    | CatDatabaseInfra                 -- ^ database CloudFormation + management scripts
    | CatPackageManagement             -- ^ language package set / artifact management
    | CatAssetsNonCode                 -- ^ non-code asset repos (prompts, images, legal, ...)
    -- Status
    | CatExperimental                  -- ^ standalone / research, not yet wired in
    | CatUnknown                       -- ^ catch-all (should be empty in steady state)
    deriving stock (Eq, Ord, Show, Enum, Bounded)

-- | Every category in render order.
allCategories :: [Category]
allCategories = [minBound .. maxBound]

-- | Markdown @## ...@ heading for a category.
categoryHeading :: Category -> Text
categoryHeading = \case
    CatKritickProduct          -> "kritick-* — product apps (customer-facing)"
    CatKritickProductSensitive -> "kritick-* — supporting assets (sensitive)"
    CatKritickService          -> "kritick-* — services"
    CatKritickCoordination     -> "kritick-* — coordination"
    CatKrikit                  -> "krikit-* — ops / agent infrastructure"
    CatKritickSchema           -> "Schema (kritick) — generator + autogen outputs + hardcoded"
    CatPureScriptKritickData   -> "purescript-kritick-*-data — kritick-domain data types"
    CatPureScriptKritickReact  -> "purescript-kritick-react-* — kritick-themed React components"
    CatPureScriptKritickOther  -> "purescript-kritick-* — kritick-domain programs / utilities"
    CatPureScriptFree          -> "purescript-*-free — Free-monad interpreters"
    CatPureScriptData          -> "purescript-*-data — pure data / value-type libraries"
    CatPureScriptReact         -> "purescript-react-* — React (web) bindings"
    CatPureScriptReactNative   -> "purescript-react-native-* — React Native bindings"
    CatPureScriptCodecs        -> "purescript-* — codecs / wire formats"
    CatPureScriptStandards     -> "purescript-* — ISO standards"
    CatPureScriptDateTime      -> "purescript-* — date / time"
    CatPureScriptGeographic    -> "purescript-* — geographic"
    CatPureScriptIdentifiers   -> "purescript-* — identifier types"
    CatPureScriptOther         -> "purescript-* — other libraries"
    CatScalaKritick            -> "scala-kritick-* — kritick-domain Scala libraries"
    CatScalaFree               -> "scala-*-free — Free-monad interpreters (server-side)"
    CatScalaData               -> "scala-*-data — Scala data libraries"
    CatScalaOther              -> "scala-* — other Scala libraries"
    CatNgKritick               -> "ng-kritick-* — Angular wrappers (legacy + active)"
    CatReact                   -> "react-* / react-kritick-* — React wrappers"
    CatUtil                    -> "util-* — utility tooling"
    CatTemplate                -> "template-* — repo templates"
    CatBuildTooling            -> "Build / deploy tooling"
    CatDatabaseInfra           -> "Database infrastructure (CloudFormation + scripts)"
    CatPackageManagement       -> "Package / artifact management"
    CatAssetsNonCode           -> "Asset repos (non-code)"
    CatExperimental            -> "Experimental / pre-integration"
    CatUnknown                 -> "Uncategorized"

-- | One-paragraph description rendered under the heading. Empty
-- string means \"no blurb\"; the renderer omits the line.
categoryBlurb :: Category -> Text
categoryBlurb = \case
    CatKritickProduct          -> "Customer-facing apps: SPAs, the customer mobile app, and the admin SPA + admin backend in `kritick-admin`."
    CatKritickProductSensitive -> "Supporting assets for kritick product repos with sensitive contents (signing certificates, private keys). **Inventoried by name only -- do NOT access contents.**"
    CatKritickService          -> "Backend and supporting services in the kritick product fleet."
    CatKritickCoordination     -> "Cross-repo coordination and skills."
    CatKrikit                  -> "Top-level ops and agent infrastructure repos."
    CatKritickSchema           -> "Schema family: the generator (`util-kritick-schema`) plus its per-language autogen outputs (`*-kritick-{,key-,feature-}schema`) plus the manually-maintained hardcoded MongoDB collection schemas (`*-kritick-collection-schema`). Per-row notes mark which is which. The data source is a schema-definition spreadsheet."
    CatPureScriptKritickData   -> "Domain ADTs for kritick: `purescript-kritick-<concept>-data`. Carries validated, typed values through the core logic."
    CatPureScriptKritickReact  -> "Kritick-themed React UI components in PureScript (button, formfield, image, qrcode, spinner, timeframe, ...)."
    CatPureScriptKritickOther  -> "Kritick-domain PureScript libraries that do not fit `-data` or `react-*`: programs, date utilities, email templates."
    CatPureScriptFree          -> "Each hides one volatile external decision behind a sum-type ADT, interpreting to Aff at the edges."
    CatPureScriptData          -> "Domain types not tied to a specific external integration."
    CatPureScriptReact         -> "PureScript wrappers for React libraries and components (web). React Native bindings are split into a separate category."
    CatPureScriptReactNative   -> "PureScript wrappers for React Native components. Consumed by `kritick-customer` (the mobile app)."
    CatPureScriptCodecs        -> "Encoding and wire-format libraries (base64, hex, argonaut JSON extensions, foreign XML, Amazon Ion, htmlstring, color hexstring)."
    CatPureScriptStandards     -> "PureScript bindings for ISO standards: 3166 (countries), 4217 (currencies), 639 (languages), 8601 (date / time)."
    CatPureScriptDateTime      -> "Date / time value types and formatting helpers."
    CatPureScriptGeographic    -> "Geographic value types: coordinates, geohash, GeoJSON."
    CatPureScriptIdentifiers   -> "Identifier-shaped string types: UUIDs, slugs, JWTs, opaque ids, numeric strings, APNS device tokens."
    CatPureScriptOther         -> "Remaining PureScript libraries (DOM helpers, forms, logging, Sentry, AWS Lambda runtime, ...)."
    CatScalaKritick            -> "Kritick-domain Scala libraries (data, hexastore, free-monad interpreter)."
    CatScalaFree               -> "Server-side parallels to purescript-*-free."
    CatScalaData               -> ""
    CatScalaOther              -> ""
    CatNgKritick               -> "Pattern: ng-kritick-<feature>. Mostly legacy; some still active. The `ng-safe-apply` repo is folded in."
    CatReact                   -> ""
    CatUtil                    -> ""
    CatTemplate                -> ""
    CatBuildTooling            -> ""
    CatDatabaseInfra           -> "Per-database repos that store CloudFormation templates and management scripts. **Not data schemas** despite the `-schema` suffix; the actual schema lives in `Schema (kritick)`."
    CatPackageManagement       -> "Repos that manage language-level dependency resolution (PureScript 0.13 package set, Maven artifact metadata)."
    CatAssetsNonCode           -> "Non-code asset repos consumed by services and product. LLM prompt corpus, static media (images), and legal documents (T&C, etc.)."
    CatExperimental            -> "Standalone or research projects under evaluation, not yet wired into the kritick / krikit ecosystem proper. Listed for awareness; expect status to change."
    CatUnknown                 -> "Repos that do not match any known prefix rule. If anything lands here, either add it to `kritick-ecosystem/config/ecosystem.json` `ignore` (if it should be excluded) or extend the taxonomy in `Krikit.Agent.Ops.RepoInventory.Run.classify`."

-- | Optional inline note rendered next to a specific repo entry.
-- Used for caveats that are repo-specific rather than category-wide
-- (e.g. \"sensitive: do not access contents\", \"hardcoded vs autogen\").
--
-- The same note is rendered for every category the repo lists in,
-- so write the note to fit both contexts.
repoNote :: Text -> Maybe Text
repoNote = \case
    -- Product oddities
    "kritick-admin" ->
        Just "**SPA + admin backend in one repo** (cross-listed in services)."
    "kritick-customer" ->
        Just "**Mobile app** (not a SPA)."
    -- Sensitive supporting
    "fastlane-ios-certificates" ->
        Just "iOS signing certificates for `kritick-customer`. **Sensitive — do not access contents.**"
    -- Schema family
    "util-kritick-schema" ->
        Just "Generator. Reads the schema-definition spreadsheet and emits per-language schema repos."
    "elasticsearch-kritick-schema" ->
        Just "Stores Elasticsearch CloudFormation + management scripts (database infra). The mapping files are autogenerated by `util-kritick-schema`."
    "purescript-kritick-schema" ->
        Just "Autogenerated by `util-kritick-schema`. Do not edit; regenerated from the schema spreadsheet."
    "purescript-kritick-key-schema" ->
        Just "Redis key-schema autogenerated by `util-kritick-schema`."
    "purescript-kritick-feature-schema" ->
        Just "Feature-key schema autogenerated by `util-kritick-schema`."
    "scala-kritick-schema" ->
        Just "Autogenerated by `util-kritick-schema`. Do not edit; regenerated from the schema spreadsheet."
    "scala-kritick-key-schema" ->
        Just "Redis key-schema autogenerated by `util-kritick-schema`."
    "scala-kritick-feature-schema" ->
        Just "Feature-key schema autogenerated by `util-kritick-schema`."
    "purescript-kritick-collection-schema" ->
        Just "Hardcoded MongoDB collection names / schemas (manually maintained)."
    "scala-kritick-collection-schema" ->
        Just "Hardcoded MongoDB collection names / schemas (manually maintained)."
    -- Email templates
    "purescript-kritick-email-templates" ->
        Just "PureScript modules implementing email templates rendered by `kritick-email`."
    -- Database infra
    "mongodb-kritick-schema" ->
        Just "MongoDB CloudFormation + management scripts (not a data schema despite the suffix)."
    "redis-kritick-schema" ->
        Just "Redis CloudFormation + management scripts (not a data schema despite the suffix)."
    -- Package / artifact management
    "purescript-package-sets" ->
        Just "Manages the PureScript 0.13 package set used across the ecosystem."
    "scala-maven-artifacts" ->
        Just "Maven artifact metadata for the Scala ecosystem."
    -- Non-code assets
    "aws-bedrock-prompts" ->
        Just "LLM prompt corpus (Bedrock-targeted)."
    "static-assets-kritick" ->
        Just "Images and other static media used by kritick websites + services."
    "static-legal-kritick" ->
        Just "Legal documents (T&Cs, privacy, etc.) used by kritick websites + services."
    _ -> Nothing

-- =============================================================================
-- Classification
-- =============================================================================

-- | Map a repo name to one or more categories. Order of rules
-- matters: more-specific patterns must be matched before
-- more-general ones, and multi-category cases come first so the
-- primary classifier doesn\'t shadow them.
classify :: Text -> NonEmpty Category
classify name
    -- Multi-category: must come first so they win over the
    -- single-category fallthroughs further down.
    | name == "kritick-admin"                     =
        CatKritickProduct :| [CatKritickService]
    | name == "elasticsearch-kritick-schema"      =
        CatDatabaseInfra :| [CatKritickSchema]

    -- Specific kritick-* known names
    | name `elem` kritickCoordRepos               = single CatKritickCoordination
    | name `elem` kritickProductRepos             = single CatKritickProduct
    | name `elem` kritickSensitiveRepos           = single CatKritickProductSensitive

    -- Schema family + database infra (must come before generic
    -- prefix rules and the kritick-domain split)
    | name `elem` kritickSchemaRepos              = single CatKritickSchema
    | name `elem` databaseInfraRepos              = single CatDatabaseInfra

    -- Build / asset / package known names (specific before generic)
    | name `elem` buildToolingRepos               = single CatBuildTooling
    | name `elem` packageManagementRepos          = single CatPackageManagement
    | name `elem` assetsNonCodeRepos              = single CatAssetsNonCode

    -- Other ecosystem-relevant known-name lookups
    | name `elem` ngKritickAdjacentRepos          = single CatNgKritick
    | name `elem` experimentalRepos               = single CatExperimental

    -- Remaining kritick-* are services
    | "kritick-" `T.isPrefixOf` name              = single CatKritickService

    -- krikit-* (note the spelling difference: krikit, not kritick)
    | "krikit-" `T.isPrefixOf` name               = single CatKrikit

    -- PureScript kritick-domain split (data / react / other)
    | psKritickDataMatch name                     = single CatPureScriptKritickData
    | "purescript-kritick-react-" `T.isPrefixOf` name
                                                  = single CatPureScriptKritickReact
    | "purescript-kritick-" `T.isPrefixOf` name   = single CatPureScriptKritickOther

    -- PureScript React Native (more specific than purescript-react-).
    -- Match the bare `purescript-react-native` plus the dashed
    -- `purescript-react-native-*` family.
    | name == "purescript-react-native"           = single CatPureScriptReactNative
    | "purescript-react-native-" `T.isPrefixOf` name
                                                  = single CatPureScriptReactNative
    | "purescript-react-" `T.isPrefixOf` name     = single CatPureScriptReact
    -- Catches purescript-cloudinary-react / purescript-flexbox-react
    -- (React-related but missed by the prefix above).
    | "purescript-" `T.isPrefixOf` name && "-react" `T.isSuffixOf` name
                                                  = single CatPureScriptReact

    -- PureScript -free / -data
    | "purescript-" `T.isPrefixOf` name && "-free" `T.isSuffixOf` name
                                                  = single CatPureScriptFree
    | "purescript-" `T.isPrefixOf` name && "-data" `T.isSuffixOf` name
                                                  = single CatPureScriptData

    -- PureScript substructure for "other"
    | name `elem` purescriptCodecRepos            = single CatPureScriptCodecs
    | name `elem` purescriptStandardsRepos        = single CatPureScriptStandards
    | name `elem` purescriptDateTimeRepos         = single CatPureScriptDateTime
    | name `elem` purescriptGeographicRepos       = single CatPureScriptGeographic
    | name `elem` purescriptIdentifiersRepos      = single CatPureScriptIdentifiers
    | "purescript-" `T.isPrefixOf` name           = single CatPureScriptOther

    -- Scala
    | "scala-kritick-" `T.isPrefixOf` name        = single CatScalaKritick
    | "scala-" `T.isPrefixOf` name && "-free" `T.isSuffixOf` name
                                                  = single CatScalaFree
    | "scala-" `T.isPrefixOf` name && "-data" `T.isSuffixOf` name
                                                  = single CatScalaData
    | "scala-" `T.isPrefixOf` name                = single CatScalaOther

    -- Angular
    | "ng-kritick-" `T.isPrefixOf` name           = single CatNgKritick

    -- React
    | "react-" `T.isPrefixOf` name                = single CatReact

    -- Utility
    | "util-" `T.isPrefixOf` name                 = single CatUtil

    -- Templates
    | "template-" `T.isPrefixOf` name             = single CatTemplate

    -- Catch-all
    | otherwise                                   = single CatUnknown
  where
    single c = c :| []

    -- Suffix predicate for `purescript-kritick-...-data` that
    -- doesn\'t false-positive on `purescript-kritick-react-formfield`
    -- etc.: must start with the kritick prefix AND end with -data.
    psKritickDataMatch :: Text -> Bool
    psKritickDataMatch n =
        "purescript-kritick-" `T.isPrefixOf` n && "-data" `T.isSuffixOf` n

-- ---------------------------------------------------------------------------
-- Known-name lookup tables
-- ---------------------------------------------------------------------------

kritickCoordRepos :: [Text]
kritickCoordRepos =
    [ "kritick-ecosystem"
    ]

-- | Customer-facing product apps -- SPAs, the mobile app, the
-- admin combined SPA+backend.
--
-- Note: @kritick-admin@ is *also* listed (as a multi-category
-- entry) in the classifier above because it is both a SPA and an
-- admin backend service. Kept here for completeness so the bare
-- product-list reads correctly.
kritickProductRepos :: [Text]
kritickProductRepos =
    [ "kritick-admin"
    , "kritick-blog"
    , "kritick-customer"
    , "kritick-help"
    , "kritick-manager"
    , "kritick-public"
    , "kritick-representative"
    , "kritick-session"
    ]

-- | Supporting assets for product repos with sensitive contents.
kritickSensitiveRepos :: [Text]
kritickSensitiveRepos =
    [ "fastlane-ios-certificates"
    ]

-- | Schema family: generator + autogen outputs + hardcoded
-- collection schemas.
--
-- @elasticsearch-kritick-schema@ is *also* in this set in spirit
-- but is handled as a multi-category entry above so it lists
-- under both Schema and Database infra.
kritickSchemaRepos :: [Text]
kritickSchemaRepos =
    [ "util-kritick-schema"
    , "purescript-kritick-schema"
    , "purescript-kritick-key-schema"
    , "purescript-kritick-feature-schema"
    , "purescript-kritick-collection-schema"
    , "scala-kritick-schema"
    , "scala-kritick-key-schema"
    , "scala-kritick-feature-schema"
    , "scala-kritick-collection-schema"
    ]

-- | Database infrastructure repos (CloudFormation + management
-- scripts). Despite the @-schema@ suffix on the names, these are
-- not data schemas.
databaseInfraRepos :: [Text]
databaseInfraRepos =
    [ "mongodb-kritick-schema"
    , "redis-kritick-schema"
    ]

buildToolingRepos :: [Text]
buildToolingRepos =
    [ "aws-cloudformation-kritick"
    , "aws-deploy-kritick"
    , "aws-deploy-kritick-webpack-plugin"
    , "aws-publish-spa-kritick-webpack-plugin"
    , "eslint-config-kritick"
    , "git-bower"
    , "git-hooks"
    , "npm-build-version-kritick"
    , "rollup-plugin-aws-deploy-kritick"
    ]

-- | Repos that manage language-level dependency resolution.
packageManagementRepos :: [Text]
packageManagementRepos =
    [ "purescript-package-sets"
    , "scala-maven-artifacts"
    ]

-- | Non-code asset repos consumed by services / product.
assetsNonCodeRepos :: [Text]
assetsNonCodeRepos =
    [ "aws-bedrock-prompts"
    , "static-assets-kritick"
    , "static-legal-kritick"
    ]

-- | Active ng-* repos that do not match the @ng-kritick-@ prefix
-- but are part of the ecosystem.
ngKritickAdjacentRepos :: [Text]
ngKritickAdjacentRepos =
    [ "ng-safe-apply"
    ]

-- | Standalone or research projects sitting in the workspace but
-- not yet integrated into the kritick / krikit ecosystem.
experimentalRepos :: [Text]
experimentalRepos =
    [ "autocoder"
    ]

-- | Encoding / wire-format libraries.
purescriptCodecRepos :: [Text]
purescriptCodecRepos =
    [ "purescript-amzn-ion"
    , "purescript-argonaut-codecs-extended"
    , "purescript-base64-string"
    , "purescript-base64-utf8"
    , "purescript-codec-argonaut-extended"
    , "purescript-color-hexstring"
    , "purescript-foreign-xml"
    , "purescript-hexstring"
    , "purescript-htmlstring"
    ]

-- | ISO standards.
purescriptStandardsRepos :: [Text]
purescriptStandardsRepos =
    [ "purescript-iso3166"
    , "purescript-iso4217"
    , "purescript-iso639"
    , "purescript-iso8601"
    ]

-- | Date / time value types and formatting helpers.
purescriptDateTimeRepos :: [Text]
purescriptDateTimeRepos =
    [ "purescript-birthdate-ymd"
    , "purescript-dateformat"
    , "purescript-epoch-milliseconds"
    , "purescript-unix-time"
    ]

-- | Geographic value types.
purescriptGeographicRepos :: [Text]
purescriptGeographicRepos =
    [ "purescript-geographic-coordinate"
    , "purescript-geohash"
    , "purescript-geojson"
    ]

-- | Identifier-shaped string types.
purescriptIdentifiersRepos :: [Text]
purescriptIdentifiersRepos =
    [ "purescript-apns-device-token"
    , "purescript-jwtstring"
    , "purescript-numericstring"
    , "purescript-opaque-identifier"
    , "purescript-slug-string"
    , "purescript-uuidstring"
    ]

-- =============================================================================
-- EcosystemFilter (consults kritick-ecosystem/config/ecosystem.json)
-- =============================================================================

-- | Filter rules read from @kritick-ecosystem\/config\/ecosystem.json@.
-- Three fields the generator + verifier respect:
--
--   * @ignore@ -- exact repo names to drop entirely (regen + verify).
--   * @skip_repo_prefixes@ -- prefixes to drop entirely (regen +
--     verify).
--   * @auto_roots.exclude_repos@ -- @kritick-*@ repos that *are*
--     part of the ecosystem but are intentionally NOT auto-roots
--     (e.g., @kritick-ecosystem@ is the meta-repo, not an app /
--     service). The repo-inventory verifier subtracts these from
--     the on-disk side before comparing to
--     @ecosystem-roots.generated.md@; the regen does NOT
--     (these repos still belong in the agent-facing inventory).
--
-- Matches @ecosystem_scan.py@ semantics: lines 693, 710-711 for the
-- first two fields; line 701 for @auto_roots.exclude_repos@.
data EcosystemFilter = EcosystemFilter
    { efIgnoreNames    :: !(Set Text)
    , efIgnorePrefixes :: ![Text]
    , efRootExceptions :: !(Set Text)
    }
    deriving stock (Eq, Show)

instance FromJSON EcosystemFilter where
    parseJSON = A.withObject "EcosystemConfig" $ \o -> do
        ignores  <- fromMaybe [] <$> o .:? "ignore"
        prefixes <- fromMaybe [] <$> o .:? "skip_repo_prefixes"
        autoO    <- fromMaybe (A.Object mempty) <$> o .:? "auto_roots"
        rootEx   <- A.withObject "auto_roots"
                        (\ar -> fromMaybe [] <$> ar .:? "exclude_repos")
                        autoO
        pure EcosystemFilter
            { efIgnoreNames    = Set.fromList ignores
            , efIgnorePrefixes = prefixes
            , efRootExceptions = Set.fromList rootEx
            }

readEcosystemFilter :: FilePath -> IO (Either Text EcosystemFilter)
readEcosystemFilter path = do
    result <- try (LBS.readFile path)
    case result of
        Left (e :: IOException) ->
            pure (Left ("could not read " <> T.pack path <> ": " <> T.pack (show e)))
        Right bytes -> case A.eitherDecode bytes of
            Left err  -> pure (Left ("could not parse " <> T.pack path <> ": " <> T.pack err))
            Right cfg -> pure (Right cfg)

applyFilter :: EcosystemFilter -> [Text] -> [Text]
applyFilter EcosystemFilter{..} = filter keep
  where
    keep n = not (n `Set.member` efIgnoreNames)
          && not (any (`T.isPrefixOf` n) efIgnorePrefixes)

-- =============================================================================
-- Inventory
-- =============================================================================

-- | The classified inventory: repos grouped under each category in
-- the canonical 'allCategories' order, with each category\'s repo
-- list sorted ascending. Multi-category repos appear in every
-- category they classify to.
newtype Inventory = Inventory
    { invByCategory :: Map Category [Text]
    }
    deriving stock (Eq, Show)

-- | Build the inventory from a flat repo-name list. Duplicates are
-- collapsed, results sorted. A repo classified to multiple
-- categories appears once in each category\'s list.
buildInventory :: [Text] -> Inventory
buildInventory names =
    Inventory
        { invByCategory =
            Map.map (sort . nub) $
                foldr insertOne Map.empty names
        }
  where
    insertOne :: Text -> Map Category [Text] -> Map Category [Text]
    insertOne n acc =
        let cats = NE.toList (classify n)
        in  foldr (\c m -> Map.insertWith (++) c [n] m) acc cats

-- | Pull the @repo@ column out of @ecosystem-roots.generated.md@.
-- The file's table layout is fixed by the generator on the
-- ecosystem side; if it changes we want a *parse* failure, not a
-- silent empty list, so we look up by header name.
extractEcosystemRoots :: Text -> [Text]
extractEcosystemRoots doc = case extractFirstTable doc of
    Nothing  -> []
    Just tbl -> case headerIndex "repo" (mtHeaders tbl) of
        Nothing  -> []
        Just idx ->
            filter (not . T.null)
                . map (cleanRepoCell . safeIdx idx)
                $ mtRows tbl
  where
    headerIndex :: Text -> [Text] -> Maybe Int
    headerIndex h hs = go 0 (map T.toLower hs)
      where
        go _ [] = Nothing
        go i (x : xs)
            | x == T.toLower h = Just i
            | otherwise        = go (i + 1) xs

    safeIdx :: Int -> [Text] -> Text
    safeIdx i row
        | i < length row = row !! i
        | otherwise      = ""

    -- A repo cell may be a markdown link: @[name](url)@. Strip if so.
    cleanRepoCell :: Text -> Text
    cleanRepoCell t =
        let stripped = T.strip t
        in  case T.stripPrefix "[" stripped of
                Just rest -> T.takeWhile (/= ']') rest
                Nothing   -> stripped

-- =============================================================================
-- Rendering
-- =============================================================================

renderInventory :: Text -> Inventory -> Text
renderInventory isoDate inv =
    T.unlines $
        [ "# Repo inventory (categorized)"
        , ""
        , renderBanner banner
        , ""
        , introBlurb
        , ""
        ]
        ++ concatMap renderCategory allCategories
  where
    banner = Banner
        { banGeneratorName = "krikit-regen-repo-inventory"
        , banInputs        =
            [ BannerInputs "`kritick-ecosystem/docs/ecosystem-roots.generated.md` (canonical kritick-* roots)"
            , BannerInputs "filesystem walk of the configured workspace root (default `~opsadmin/Development/`)"
            , BannerInputs "`kritick-ecosystem/config/ecosystem.json` (`ignore` + `skip_repo_prefixes` filter)"
            ]
        , banTrigger       = "on `ecosystem-roots.generated.md` change + cron 06:35 daily fallback"
        , banLastGenerated = isoDate
        }

    introBlurb = T.unlines
        [ "Categorized view of the kritick / krikit repo ecosystem."
        , "The canonical exhaustive inventory with metadata lives in"
        , "`kritick-ecosystem/docs/ecosystem-roots.generated.md`;"
        , "this file is the agent-facing categorized derived view."
        , ""
        , "Some repos appear in more than one section because they"
        , "are genuinely multi-faceted (e.g., `kritick-admin` is a"
        , "SPA + admin backend; `elasticsearch-kritick-schema` is"
        , "database infra + autogenerated mappings). Cross-references"
        , "are intentional, not duplication."
        , ""
        , "For category definitions and naming conventions, see"
        , "`kritick-domain-knowledge.md`."
        ]

    renderCategory cat =
        case Map.lookup cat (invByCategory inv) of
            Nothing    -> []          -- empty bucket: omit the section entirely
            Just repos ->
                [ "## " <> categoryHeading cat
                , ""
                ]
                ++ blurbLines cat
                ++ map renderEntry repos
                ++ [""]

    renderEntry r = case repoNote r of
        Nothing   -> "- `" <> r <> "`"
        Just note -> "- `" <> r <> "` — " <> note

    blurbLines cat =
        let b = categoryBlurb cat
        in  if T.null b then [] else [b, ""]

-- =============================================================================
-- Effectful orchestrator
-- =============================================================================

-- | End-to-end regen: pull paths from @'Reader' 'Config'@, read the
-- canonical inputs, classify, write idempotently. Returns
-- @'Left' err@ on input failure or @'Right' outcome@ on success.
regenerate
    :: ( Reader Config :> es
       , IOE :> es
       )
    => Eff es (Either Text (FilePath, WriteOutcome))
regenerate = do
    cfg <- ask
    let rootsPath = epEcosystemRootsMd  . pcEcosystem . cfgPaths $ cfg
        ecoPath   = epEcosystemJson     . pcEcosystem . cfgPaths $ cfg
        outPath   = fpRepoInventoryMd   . pcFabric    . cfgPaths $ cfg
        wsRoot    = cfgWorkspaceRoot cfg

    today    <- liftIO isoDateUTC
    rootsDoc <- liftIO (TIO.readFile rootsPath)
    fsRepos  <- liftIO (listRepoDirs wsRoot)
    filterE  <- liftIO (readEcosystemFilter ecoPath)
    case filterE of
        Left err -> pure (Left err)
        Right f  -> do
            let kritickRepos = extractEcosystemRoots rootsDoc
                allRepos     = applyFilter f (kritickRepos ++ fsRepos)
                inv          = buildInventory allRepos
                body         = renderInventory today inv
            outcome <- liftIO (writeIfChanged outPath body)
            pure (Right (outPath, outcome))

-- | Today\'s date in @YYYY-MM-DD@. Used only for the banner\'s
-- @Last generated@ line; the writer scrubs that line during
-- idempotency comparison.
isoDateUTC :: IO Text
isoDateUTC = do
    now <- Time.getCurrentTime
    pure (T.pack (Time.showGregorian (Time.utctDay now)))
