{-# LANGUAGE OverloadedStrings #-}

-- | Auto-generation banner shared across every @*.generated.md@ file.
--
-- Every regenerated artifact begins with a "do not edit" banner whose
-- shape is fixed by convention (see
-- @rfc-agentops-automations.md@ "Regeneration automations"). This module
-- assembles that banner from the per-generator bits so we don't have to
-- maintain the boilerplate in each generator's prose.
module Krikit.Agent.Ops.Regen.Banner
    ( -- * Domain types
      Banner (..)
    , BannerInputs (..)

      -- * Rendering
    , renderBanner
    , normalizeForCompare
    , lastGeneratedPrefix
    ) where

import           Data.Text       (Text)
import qualified Data.Text       as T

-- | Identification + cadence + provenance for one generator. Pure
-- data; the generator decides what to fill in.
data Banner = Banner
    { banGeneratorName :: !Text
      -- ^ e.g. @"krikit-regen-system-state-mini"@
    , banInputs        :: ![BannerInputs]
      -- ^ canonical sources the generator reads from
    , banTrigger       :: !Text
      -- ^ human-readable description of when this regenerates
    , banLastGenerated :: !Text
      -- ^ ISO date / mode marker, e.g. @"2026-04-29"@. Stripped during
      -- idempotency comparison so wall-clock bumps don't churn the file.
    }
    deriving (Eq, Show)

-- | One canonical input the generator reads from. Free-form prose so
-- we can mention paths, repos, or live APIs uniformly.
newtype BannerInputs = BannerInputs { unBannerInputs :: Text }
    deriving (Eq, Show)

-- | Render a banner as a Markdown blockquote suitable to drop in at
-- the top of a @.generated.md@ file (after the @# Title@ line).
renderBanner :: Banner -> Text
renderBanner b =
    T.unlines $
        [ "> ⚠️ **Auto-generated.** Regenerated by `"
            <> banGeneratorName b
            <> "`"
        , "> (Haskell binary in `krikit-agent-ops`)."
        ]
        ++ inputsBlock
        ++
        [ ">"
        , "> **Do not edit directly.** Manual edits will be overwritten"
        , "> on the next regeneration."
        , ">"
        , "> Trigger: " <> banTrigger b <> "."
        , "> " <> lastGeneratedPrefix <> " " <> banLastGenerated b
        ]
  where
    inputsBlock = case banInputs b of
        []  -> []
        [x] -> [">", "> Source: " <> unBannerInputs x]
        xs  ->
            [ ">"
            , "> Sources:"
            ]
            ++ map (\(BannerInputs t) -> "> - " <> t) xs

-- | Marker prefix for the wall-clock line. Centralized so
-- 'normalizeForCompare' and the writer agree on what to scrub.
lastGeneratedPrefix :: Text
lastGeneratedPrefix = "Last generated:"

-- | Drop the "Last generated: ..." line so two renderings whose only
-- difference is the date compare equal.
normalizeForCompare :: Text -> Text
normalizeForCompare =
    T.unlines . map scrub . T.lines
  where
    scrub line
        | lastGeneratedPrefix `T.isInfixOf` line = "> " <> lastGeneratedPrefix <> " <normalized>"
        | otherwise = line
